### ISSUE TITLE
Error on arm64

### ISSUE THREAD

**Issue by fnoop** [cdr/nbin#24]
```
+ node /srv/maverick/var/build/codeserver/scripts/nbin.js /srv/maverick/var/build/codeserver/build/code-serverproduction-vsc1.38.1-linux-aarch64-built linux code-serverproduction-vsc1.38.1-linux-aarch64
✔ Wrote 4514 files!
info  Fetching {"url":"https://nbin.cdr.sh/1.2.2/node-10.15.1-linux-arm64"}
Error: Forbidden
    at e.Binary.<anonymous> (/srv/maverick/var/build/codeserver/node_modules/@coder/nbin/out/api.js:1:43464)
    at Generator.next (<anonymous>)
    at s (/srv/maverick/var/build/codeserver/node_modules/@coder/nbin/out/api.js:1:40627)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is because https://nbin.cdr.sh/1.2.2/node-10.15.1-linux-arm64 returns an 'Access Denied' error.

**Comment by fnoop** [comment]
Ah, I see this is in progress: https://github.com/cdr/nbin/pull/23
